server {
    listen 8080;
    server_name localhost;
    autoindex on;
    server_tokens on;
    location / {
        root /var/www/html;
    }

    location /config/ {
        autoindex on;
        allow all;
    }

    location /logs/ {
        autoindex on;
        allow all;
    }
}
